//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindyFarm.Resources.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindyFarm.Resources.lang.en-US.Resource", typeof(en_US_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been logged-in on other session!.
        /// </summary>
        internal static string AccountUsedByOther {
            get {
                return ResourceManager.GetString("AccountUsedByOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found. Please create character!.
        /// </summary>
        internal static string CharacterNotFound {
            get {
                return ResourceManager.GetString("CharacterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation does not match!.
        /// </summary>
        internal static string ConfirmationPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmationPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some internal error occur on the server, please try again after few seconds!.
        /// </summary>
        internal static string DatabaseInternalError {
            get {
                return ResourceManager.GetString("DatabaseInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name has been used by other player!.
        /// </summary>
        internal static string DisplayNameDuplicated {
            get {
                return ResourceManager.GetString("DisplayNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format must be &apos;example@gmail.com!&apos;.
        /// </summary>
        internal static string EmailFormatInvalid {
            get {
                return ResourceManager.GetString("EmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been use for other account!.
        /// </summary>
        internal static string EmailHasBeenUsed {
            get {
                return ResourceManager.GetString("EmailHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect!.
        /// </summary>
        internal static string IncorrectLoginInfo {
            get {
                return ResourceManager.GetString("IncorrectLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test..........
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long, contain at least one uppercase, lowercase, and number!.
        /// </summary>
        internal static string ViolationOfPasswordPrivacyPolicy {
            get {
                return ResourceManager.GetString("ViolationOfPasswordPrivacyPolicy", resourceCulture);
            }
        }
    }
}
